//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_INFORMATION
    {
        public CLIENT_INFORMATION()
        {
            this.RESERVATION_INFORMATION = new HashSet<RESERVATION_INFORMATION>();
            this.ROOM_INFORMATION = new HashSet<ROOM_INFORMATION>();
        }
    
        public int clientID { get; set; }
        public string clientfName { get; set; }
        public string clientLname { get; set; }
        public string clientEmail { get; set; }
        public string clientPhone { get; set; }
        public string clientAddress { get; set; }
    
        public virtual ICollection<RESERVATION_INFORMATION> RESERVATION_INFORMATION { get; set; }
        public virtual ICollection<ROOM_INFORMATION> ROOM_INFORMATION { get; set; }
    }
}
