//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUEST
    {
        public GUEST()
        {
            this.RESERVATION = new HashSet<RESERVATION>();
        }
    
        public int guestID { get; set; }
        public int guestAdult { get; set; }
        public int guestChildren { get; set; }
        public int guestSeniorCitizen { get; set; }
    
        public virtual ICollection<RESERVATION> RESERVATION { get; set; }
    }
}
