//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public PAYMENT()
        {
            this.RESERVATION = new HashSet<RESERVATION>();
        }
    
        public int paymentID { get; set; }
        public System.DateTime paymentDate { get; set; }
        public int paymentTotal { get; set; }
    
        public virtual ICollection<RESERVATION> RESERVATION { get; set; }
    }
}
