//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_INFORMATION
    {
        public PAYMENT_INFORMATION()
        {
            this.ROOM_INFORMATION = new HashSet<ROOM_INFORMATION>();
        }
    
        public int paymentID { get; set; }
        public System.DateTime paymentDate { get; set; }
        public string paymentMethod { get; set; }
        public decimal paymentTotal { get; set; }
    
        public virtual ICollection<ROOM_INFORMATION> ROOM_INFORMATION { get; set; }
    }
}
