//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION_INFORMATION
    {
        public RESERVATION_INFORMATION()
        {
            this.CLIENT_INFORMATION = new HashSet<CLIENT_INFORMATION>();
        }
    
        public int reservationID { get; set; }
        public System.DateTime reservationDateIn { get; set; }
        public System.DateTime reservationDateOut { get; set; }
        public string reservationStatus { get; set; }
        public Nullable<int> roomNumber { get; set; }
    
        public virtual ICollection<CLIENT_INFORMATION> CLIENT_INFORMATION { get; set; }
        public virtual ROOM_INFORMATION ROOM_INFORMATION { get; set; }
    }
}
