//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        public RESERVATION()
        {
            this.ROOM = new HashSet<ROOM>();
        }
    
        public int reservationID { get; set; }
        public Nullable<int> noOfGuest { get; set; }
        public string typeOfGuest { get; set; }
        public System.DateTime reservationDateIn { get; set; }
        public System.DateTime reservationDateOut { get; set; }
        public string reservationStatus { get; set; }
        public Nullable<int> noOfDays { get; set; }
        public int paymentID { get; set; }
        public int clientID { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual ICollection<ROOM> ROOM { get; set; }
    }
}
