//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public ROLE()
        {
            this.ACCOUNTS = new HashSet<ACCOUNTS>();
        }
    
        public int roleID { get; set; }
        public string roleName { get; set; }
        public string roleDescription { get; set; }
    
        public virtual ICollection<ACCOUNTS> ACCOUNTS { get; set; }
    }
}
