//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM_INFORMATION
    {
        public ROOM_INFORMATION()
        {
            this.RESERVATION_INFORMATION = new HashSet<RESERVATION_INFORMATION>();
        }
    
        public int roomNumber { get; set; }
        public string roomType { get; set; }
        public Nullable<int> paymentID { get; set; }
    
        public virtual PAYMENT_INFORMATION PAYMENT_INFORMATION { get; set; }
        public virtual ICollection<RESERVATION_INFORMATION> RESERVATION_INFORMATION { get; set; }
    }
}
