//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public int roomID { get; set; }
        public string roomType { get; set; }
        public int reservationID { get; set; }
    
        public virtual RESERVATION RESERVATION { get; set; }
    }
}
