//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM_INFORMATION
    {
        public int roomNumber { get; set; }
        public string roomType { get; set; }
        public Nullable<int> clientID { get; set; }
    
        public virtual CLIENT_INFORMATION CLIENT_INFORMATION { get; set; }
    }
}
