//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM_DETAILS
    {
        public int roomID { get; set; }
        public string roomType { get; set; }
        public byte[] roomPhoto { get; set; }
        public double roomPrice { get; set; }
        public string roomDetails { get; set; }
        public double roomDiscount { get; set; }
        public double discountedPrice { get; set; }
    }
}
