//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERLOGGED_HISTORY
    {
        public int userlogID { get; set; }
        public string typeofAccount { get; set; }
        public System.DateTime dateLogin { get; set; }
        public System.TimeSpan timeLogin { get; set; }
        public string lastActivity { get; set; }
    }
}
