//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_display_room_details
    {
        public int ID { get; set; }
        public string RoomType { get; set; }
        public string Details { get; set; }
        public decimal Price { get; set; }
        public string Promo { get; set; }
        public decimal Discounted { get; set; }
    }
}
