//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_display_total_approve_guest
    {
        public int guestID { get; set; }
        public Nullable<int> TotalAdult { get; set; }
        public Nullable<int> TotalChildren { get; set; }
        public Nullable<int> TotalSeniorCitizen { get; set; }
        public Nullable<int> TotalGuest { get; set; }
    }
}
